### ISSUE TITLE
feat: being able to compare format values between samples in same vcf

### ISSUE THREAD

**Issue by elleira** [hydra-genetics/filtering#79]
If you have a TN vcf it would be nice to be able to filter the vcf by comparing the tumor with normal values e.g.
```
af_normal:
  description: "filter variants with AF less than twice the normal sample AF"
  expression: "FORMAT:AF[tumor_sample] < 2 * FORMAT:AF[normal_sample]"
  soft_filter: "False"

```
Right now you can only specify one sample regex as a parameter.
